variables:
  # Environment names
  DEV_ENV_NAME: 'development'
  TEST_ENV_NAME: 'test'
  DEMO_ENV_NAME: 'demo'

  VARIABLES_FILE: ${CI_PROJECT_DIR}/variables.env  # "." is required for image that have sh not bash

  # For the default QA image,  use $CI_COMMIT_SHA as tag since it's always available
  QA: "qa"
  QA_IMAGE: "${CI_REGISTRY_IMAGE}/${QA_TAG_PREFIX}:${CI_COMMIT_SHORT_SHA}"
  # Default latest tag for particular branch
  QA_IMAGE_LATEST: "${CI_REGISTRY_IMAGE}/${CI_COMMIT_REF_SLUG}/${QA_TAG_PREFIX}:latest"

  MR: "mr"
  MR_IMAGE: "${CI_REGISTRY_IMAGE}/${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}/${MR_TAG_PREFIX}:${CI_MERGE_REQUEST_ID}"
  MR_IMAGE_LATEST: "${CI_REGISTRY_IMAGE}/${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}/${MR_TAG_PREFIX}:latest"

  # Released Image Artefacts
  RELEASE: "released"
  RELEASE_IMAGE: "${CI_REGISTRY_IMAGE}/${RELEASE_TAG_PREFIX}:${CI_COMMIT_SHORT_SHA}"
  RELEASE_IMAGE_LATEST: "${CI_REGISTRY_IMAGE}/${RELEASE_TAG_PREFIX}:latest"


.build_vars:
  rules:
  # DEMO Deployment on commit to the main branch => Released images
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    variables:
      IMAGE_TYPE: $RELEASE
      IMAGE_REPO: ${CI_REGISTRY_IMAGE}/${IMAGE_TYPE}
      IMAGE_TAG: $CI_COMMIT_SHORT_SHA
      NAMESPACE: ${NAMESPACE:-DEMO_ENV_NAME} # main branches can be named differently, so using unique namespace 'demo' instead
      ENVIRONMENT: ${ENVIRONMENT:-$DEMO_ENV_NAME}
      KUBE_CONTEXT: ${KUBE_CONTEXT:-$KUBE_CONTEXT_DEMO}

  # TEST Deployment on Merge Request
  - if: $CI_MERGE_REQUEST_ID
    variables:
      IMAGE_TYPE: $MR
      IMAGE_REPO: ${CI_REGISTRY_IMAGE}/${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}/$IMAGE_TYPE
      IMAGE_TAG: $CI_MERGE_REQUEST_ID
      ENVIRONMENT: $TEST_ENV_NAME
      NAMESPACE: ${TEST_ENV_NAME}-${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}
      KUBE_CONTEXT: ${KUBE_CONTEXT:-$KUBE_CONTEXT_TEST}

  # DEVELOPMENT Deployment on commit to the feature branch
  - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE != "merge_request_event" && ($BRANCH_NAME == null || $BRANCH_NAME == $CI_COMMIT_BRANCH)
    variables:
      IMAGE_TYPE: $QA
      IMAGE_REPO: ${CI_REGISTRY_IMAGE}/${CI_COMMIT_REF_SLUG}/$IMAGE_TYPE
      IMAGE_TAG: $CI_COMMIT_SHORT_SHA
      ENVIRONMENT: $DEV_ENV_NAME
      NAMESPACE: ${DEV_ENV_NAME}-${CI_COMMIT_REF_SLUG}
#      KUBE_CONTEXT: ${KUBE_CONTEXT:-$KUBE_CONTEXT_DEV}
