stages:
- deploy-image

deploy:
  stage: deploy-image
  variables:
    UPSTREAM_PROJECT_NAME: __UPSTREAM_PROJECT_NAME__
    IMAGE_TAG: TODO
    UPSTREAM_COMMIT_BRANCH: __UPSTREAM_COMMIT_BRANCH__
    MERGE_REQUEST_TARGET_BRANCH_NAME: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    UPSTREAM_PROJECT: $CI_PROJECT_PATH
    UPSTREAM_SHORT_SHA: $CI_COMMIT_SHORT_SHA
    PIPELINE_TRIGGERED: 'true' #workaround because CI_PIPELINE_TRIGGERED is not working in GitLab! TODO
  trigger:
    project: __PROJECT__
    branch: __BRANCH__
