variables:
  VARIABLES_FILE: ${CI_PROJECT_DIR}/variables.env  # "." is required for image that have sh not bash

  # For the default QA image,  use $CI_COMMIT_SHA as tag since it's always available
  QA_IMAGE: "${CI_REGISTRY}/${CI_PROJECT_PATH}/qa:${CI_COMMIT_SHORT_SHA}"
  # Default latest tag for particular branch
  QA_IMAGE_BRANCH: "${CI_REGISTRY}/${CI_PROJECT_PATH}/qa:${CI_COMMIT_REF_SLUG}"

  MR_IMAGE: "${CI_REGISTRY}/${CI_PROJECT_PATH}/mr:${CI_MERGE_REQUEST_ID}"
  MR_IMAGE_BRANCH: "${CI_REGISTRY}/${CI_PROJECT_PATH}/mr:${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}"

  # Released Image Artefacts
  RELEASE_IMAGE: "${CI_REGISTRY}/${CI_PROJECT_PATH}/released:${CI_COMMIT_SHORT_SHA}"
  RELEASE_IMAGE_LATEST: "${CI_REGISTRY}/${CI_PROJECT_PATH}/released:latest"
