stages:
- deploy-image

deploy:
  stage: deploy-image
  rules:
  - if: $CI_MERGE_REQUEST_ID || $CI_COMMIT_TAG || $CI_COMMIT_BRANCH
    when: always
  variables:
    IMAGE: __IMAGE__
    UPSTREAM_PROJECT_NAME: __UPSTREAM_PROJECT_NAME__
    UPSTREAM_PROJECT_PATH: __UPSTREAM_PROJECT_PATH__
    ENVIRONMENT: __ENVIRONMENT__
    NAMESPACE: __NAMESPACE__
    PIPELINE_TRIGGERED: 'true' #workaround because CI_PIPELINE_TRIGGERED is not working in GitLab!
  trigger:
    project: __PROJECT__
    branch: __BRANCH__