stages:
- deploy-image

deploy:
  stage: deploy-image
  variables:
    APPLICATION: $CI_PROJECT_NAME
    IMAGE_TAG: $IMAGE
    UPSTREAM_BRANCH: $CI_COMMIT_REF_NAME
    MERGE_REQUEST_TARGET_BRANCH_NAME: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    UPSTREAM_PROJECT: $CI_PROJECT_PATH
    UPSTREAM_SHORT_SHA: $CI_COMMIT_SHORT_SHA
    PIPELINE_TRIGGERED: 'true' #workaround because CI_PIPELINE_TRIGGERED is not working in GitLab! TODO
  trigger:
    project: __PROJECT__
    branch: __BRANCH__