#
# IMPORTANT: Do not rename this file or move to another folder. Doing so would
#            break the CI pipelines of projects that "include:" this file.
#
# REF: https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#using-docker-in-docker-image-from-container-registry

# Included Variables
include:
  .gitlab-ci-build-vars.yml

image: docker:${DOCKER_IMAGE_VERSION}

services:
- docker:${DOCKER_IMAGE_VERSION}-dind

stages:
- build-image

variables:
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  DOCKER_IMAGE_VERSION: 19.03.1
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

after_script:
  - docker logout ${CI_REGISTRY}

.build_image: &build_image
  script:
  - echo "Building image with tags [$IMAGE], [$IMAGE_LATEST]"
  - docker build --pull -t ${IMAGE} -t ${IMAGE_LATEST} .
  - docker push ${IMAGE}
  - docker push ${IMAGE_LATEST}
#  - echo "export IMAGE=$IMAGE " > $VARIABLES_FILE
#  artifacts:
#    paths:
#    - ${VARIABLES_FILE}

# Release image when commit to the main branch (e.g. when merge request approved, or directly to the main branch)

build image:
  environment: $ENVIRONMENT
  stage: build-image
  <<: *build_image
  - echo "CI_MERGE_REQUEST_SOURCE_BRANCH_NAME = $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME"
  only:
    variables:
      - $IMAGE