#
# IMPORTANT: Do not rename this file or move to another folder. Doing so would
#            break the CI pipelines of projects that "include:" this file.
#

# This file is used to generate trigger yml
# This is needed in for project inside trigger to be a static string, since dynamic variable subsitution is not working.
# Also IMAGE TAG is passed as a variable
# Requires $DEPLOY_PROJECT to be set
# Included Variables
include:
  .gitlab-ci-build-vars.yml

stages:
- generate-yml
- deploy-image

#deploy:
#  stage: deploy-image
#  variables:
#    APPLICATION: $CI_PROJECT_NAME
#    IMAGE_TAG: $IMAGE
#    UPSTREAM_BRANCH: $CI_COMMIT_REF_NAME
#    MERGE_REQUEST_TARGET_BRANCH_NAME: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
#    UPSTREAM_PROJECT: $CI_PROJECT_PATH
#    UPSTREAM_SHORT_SHA: $CI_COMMIT_SHORT_SHA
#    PIPELINE_TRIGGERED: 'true' #workaround because CI_PIPELINE_TRIGGERED is not working in GitLab! TODO
#    PROJECT: $DEPLOY_PROJECT
#  rules:
#  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
#    variables:
#      IMAGE: $RELEASE_IMAGE
#      ENVIRONMENT: demo
#      TRIGGER_BRANCH: main
#  - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
#    variables:
#      IMAGE: $MR_IMAGE
#      ENVIRONMENT: test
#      TRIGGER_BRANCH: ${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}
#  - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE != "merge_request_event"
#    variables:
#      IMAGE: $QA_IMAGE
#      ENVIRONMENT: development
#      TRIGGER_BRANCH: main
#  trigger:
#    project: gcp-solutions/hcls/claims-modernization/gitlab-test-examples/deployapplications
#    #project: "${PROJECT}"  #TODO
#    branch: "${TRIGGER_BRANCH}"
variables:
  PROJECT_PATH: gcp-solutions/hcls/claims-modernization/gitlab-ci
  TRIGGER_FILE: .gitlab-ci-trigger-template.yml

create:
  stage: generate-yml
  variables:
    TRIGGER_BRANCH: "main"
    COMMIT_BRANCH: $CI_COMMIT_BRANCH
    DEPLOY_PROJECT: 'gcp-solutions/hcls/claims-modernization/gitlab-test-examples/deployapplications'
#  rules:
#  - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE != "merge_request_event"
#      variables:
#        TRIGGER_BRANCH: $CI_COMMIT_BRANCH
#  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
#      variables:
#        COMMIT_BRANCH: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
  script:
  #    variables:
  #      IMAGE: $MR_IMAGE
  #      ENVIRONMENT: test
  - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}/${PROJECT_PATH}.git $(basename ${PROJECT_PATH})
  - >
    sed 's|__DOWNSTREAM_PROJECT_PATH__|'"${DOWNSTREAM_PROJECT_PATH}"'|g; s|__DOWNSTREAM_BRANCH__|'"${DOWNSTREAM_BRANCH}"'|g;' $(basename ${PROJECT_PATH})/.gitlab-ci-trigger-template.yml > ${TRIGGER_FILE}
         s|__DOWNSTREAM_BRANCH__|'"${DOWNSTREAM_BRANCH}"'|g;
         s|__UPSTREAM_PROJECT_NAME__|'"${CI_PROJECT_NAME}"'|g;
         s|__UPSTREAM_BRANCH__|'"${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}"'|g;
         s|__UPSTREAM_MR_SOURCE_BRANCH__|'"${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}"'|g;
         s|__UPSTREAM_PROJECT_PATH__|'"${CI_PROJECT_PATH}"'|g;
         s|__UPSTREAM_SHORT_SHA__|'"${$CI_COMMIT_SHORT_SHA}"'|g;' $(basename ${PROJECT_PATH})/.gitlab-ci-trigger-template.yml > ${TRIGGER_FILE}

  - cat ${TRIGGER_FILE}
  artifacts:
    paths:
    - ${TRIGGER_FILE}

execute:
  stage: deploy-image
  trigger:
    include:
    - artifact: ${TRIGGER_FILE}
      job: create
    strategy: depend

