stages:
- deploy-image

deploy:
  stage: deploy-image
  variables:
    IMAGE: __IMAGE__
    UPSTREAM_PROJECT_NAME: __UPSTREAM_PROJECT_NAME__
    UPSTREAM_PROJECT_PATH: __UPSTREAM_PROJECT_PATH__
    ENVIRONMENT: __ENVIRONMENT__
    NAMESPACE: __NAMESPACE__
    PIPELINE_TRIGGERED: 'true' #workaround because CI_PIPELINE_TRIGGERED is not working in GitLab! TODO
  trigger:
    project: __PROJECT__
    branch: __BRANCH__
    fallback_branch: master
