#
# IMPORTANT: Do not rename this file or move to another folder. Doing so would
#            break the CI pipelines of projects that "include:" this file.
#
# REF: https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#using-docker-in-docker-image-from-container-registry

# Included Variables
include:
  .gitlab-ci-build-vars.yml

image: docker:${DOCKER_IMAGE_VERSION}

services:
- docker:${DOCKER_IMAGE_VERSION}-dind

stages:
- build-image

variables:
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  DOCKER_IMAGE_VERSION: 19.03.1
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"

.build_image: &build_image
  environment: $ENVIRONMENT
  script:
  - echo "Building Image with tags [$IMAGE], [$IMAGE_LATEST]"
  - echo CI_MERGE_REQUEST_SOURCE_BRANCH_SHA = $CI_MERGE_REQUEST_SOURCE_BRANCH_SHA
  - echo CI_MERGE_REQUEST_SOURCE_BRANCH_NAME = $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
  - echo CI_MERGE_REQUEST_TARGET_BRANCH_NAME = $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
  - echo CI_MERGE_REQUEST_DIFF_BASE_SHA = $CI_MERGE_REQUEST_DIFF_BASE_SHA
  - echo CI_DEFAULT_BRANCH = $CI_DEFAULT_BRANCH
  - echo CI_MERGE_REQUEST_ID = $CI_MERGE_REQUEST_ID
  - docker build --pull -t ${IMAGE} -t ${IMAGE_LATEST} .
  - docker push ${IMAGE}
  - docker push ${IMAGE_LATEST}
  - echo IMAGE_LATEST=${IMAGE_LATEST}, IMAGE=${IMAGE}
  - echo export IMAGE=${IMAGE} > "${VARIABLES_FILE}"
  - echo export ENVIRONMENT=$ENVIRONMENT >> "${VARIABLES_FILE}"
  - echo export NAMESPACE=$NAMESPACE >> "${VARIABLES_FILE}"
  - cat "${VARIABLES_FILE}"
  before_script:
  - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  after_script:
  - docker logout ${CI_REGISTRY}

build image:
  stage: build-image
  rules:
  - !reference [.build_rules, rules]
  <<: *build_image
  artifacts:
    paths:
    - "${VARIABLES_FILE}"

